version: "3"

services:
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6378:6379"

  metarank:
    container_name: metarank
    image: metarank/metarank:latest
    depends_on:
      - redis
    command: "standalone --config /metarank/config.yml --data /metarank/events.jsonl.gz"
    # command: "standalone --config ./codelight/config.yml --data ./codelight/candidates.jsonl.gz"
    volumes:
      - ./metarank:/metarank
      # - ./codelight:/codelight
    ports:
      - "8080:8080"
      - "6123:6123"

  metarank_codelight:
    container_name: metarank_codelight
    image: metarank/metarank:latest
    depends_on:
      - redis
    command: "standalone --config ./codelight/config.yml --data ./codelight/candidates.jsonl.gz"
    volumes:
      - ./codelight:/codelight
    ports:
      - "8080:8080"
      - "6123:6123"
